### ISSUE TITLE
plugin browser update warning: continue doesn't work.

### ISSUE THREAD

**Issue by dzjorrit** [construct-framework/bootstruct#7]
Hi!

I love this template. Only one issue: I use the plugin browser update warning.
http://extensions.joomla.org/extensions/site-management/browsers-a-web-standards/20111

It works fine on other templates but in bootstruct the continue button that should activate a java script doesn't seem to work.
I can not find out what is blocking it...
Anyone any idea?

Thanks!
Jorrit

**Comment by betweenbrain** [comment]
Hello Jorrit,

My apologies for not responding sooner. I just realized that email notifications for this repo were not working again.

I do see that the plugin is described as "100% MooTools". Since bootstruct has the ability to remove MooTools, that may be a possibility. Can you check to see if MooTools is loading.

**Comment by dzjorrit** [comment]
The owner told me there is a jquery conflict because it is not run in compatibility mode. So the description that this plugin in is only 100% MooTools is not valid anymore...

**Comment by betweenbrain** [comment]
Would you say that this issue is with the plufin and not bootstrcut then?

Best,

Matt Thomas Founder betweenbrain™ Lead Developer Construct Template
Development Framework Phone: 203.632.9322 Twitter: @betweenbrain Github:
https://github.com/betweenbrain

**Comment by dzjorrit** [comment]
Since this plugin does not have any problems in other joomla 3 templates is suggesting that something can be improved in this template. But in the end it is of course the responsibility of both template and extension designers to eliminate possible jquery conflicts...

**Comment by betweenbrain** [comment]
I agree. If problems don't exist with core templates, but do with
bootstruct, something can be improved. Core templates are the litmus test I
normally use.

Since this is a JavaScript related issue, can you tell me what the settings
of the parameters in the JavaScript pane are? Is there any chance that this
site is live somewhere that I can see?

Best,

Matt Thomas Founder betweenbrain™ Lead Developer Construct Template
Development Framework Phone: 203.632.9322 Twitter: @betweenbrain Github:
https://github.com/betweenbrain

**Comment by dzjorrit** [comment]
The javascript panel: load mootools=yes and no exeptions.
You can see the site on: http://yogadag.dk/
I did set the minimum browser version for firefox to 20 so you can always see the upgrade panel popup!
Thanks!
Jorrit

**Comment by betweenbrain** [comment]
In FireBug console, when clicking continue, I get the following JavaScript error:

```
TypeError: $(...).setStyle is not a function
```

But, I do see that all of the browser buttons work.  This seems to imply a conflict with the setScript method in the plugin, but I'm not sure where it might be. If mootools is set to Yes, bootsruct doesn't do anything.

When testing this with core templates, do you have all of the same plugins and components installed as you do right now? For example, with the facebook plugin.

I am also wondering of https://github.com/construct-framework/bootstruct/blob/master/elements/logic.php#L462 might be causing the issue. Can you try commenting that out and seeing if the issue is resolved?

**Comment by dzjorrit** [comment]
Commenting out line 464 seems to solve the problem, so it is indeed a jquery issue...

**Comment by betweenbrain** [comment]
Perfect. The issue is a jQuery conflict, and should be solved by a commit that I just made to the develop branch at https://github.com/construct-framework/bootstruct/commit/b2fc568c3bed4833cf4183d7e53f7310ce046596.

I'm working on improving bootstruct, so this kind of feedback is great. Thanks!

**Comment by dzjorrit** [comment]
Thanks for your work! Like I said before, I love this template!

**Comment by betweenbrain** [comment]
That's fantastic! I appreciate the feedback. I'm always excited to hear what people like and dislike about it. Any feedback that you can provide would be great. Thanks!
